config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  authenticated :admin do
    resources :tokens, only: [:new, :create, :destroy]
    get '/tokens/manage'
  end

  scope :api do
    namespace :v1 do
      get '/players'                  => 'players#index'
      get '/players/:id'              => 'players#show'
      get '/players/:id/recent_games' => 'players#recent_games'

      get   '/games'                  =>  'games#list'
      post  '/games'                  =>  'games#create'
      get   '/games/:id'              =>  'games#show'
      get   '/games/:gamename'        =>  'games#index'
      get   '/games/recent'           =>  'games#recent'
      get   '/games/:gamename/recent' =>  'games#recent_game'
    end
  end

  get   '/invite'   => 'static_pages#new',    as: 'new_invite'
  post  '/invite'   => 'static_pages#create', as: 'create_invite'

  root 'static_pages#home' 

end

app/models/token.rb
class Token < ActiveRecord::Base
  class Invalid < StandardError; end
  belongs_to :admin

  validates :key, presence: true, uniqueness: true
  validates_presence_of :description

  scope :valid, -> { where(active: true) }

  def disable!
    update active: false
  end

  def disabled?
    !active?
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_filter :authenticate_admin!

  

  def create
    current_admin.generate_api_token!(params[:description])
    redirect_to :back, notice: "Token generated"
  end

  def destroy
    token = current_admin.tokens.find params[:id] #check this
    token.disable!
    redirect_to :back, notice: "Token disabled"
  end

end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/manage.html.erb
<% notice %>
<h1><%= current_admin.email %></h1>

<table>
  <thead>
    <tr>
      <th> Key </th>
      <th> Disabled? </th>
    </tr>
  </thead>
  <tbody>
    <% current_admin.tokens.each do |t| %>
      <tr>
        <td><%= t.key %></td>
        <td>
          <%= t.disabled? %>
          <%= form_tag url: token_path(t), method: :delete do %>
            <button> Disable </button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<%= form_tag tokens_path do %>
  <%= label_tag :description %>
  <%= text_field_tag :description %>
  <button> Generate New Token</button>
<% end %>